apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-html-site
  labels:
    app: beginner-html-site
spec:
  replicas: 5
  selector:
    matchLabels:
      app: beginner-html-site
  template:
    metadata:
      labels:
        app: beginner-html-site
    spec:
      containers:
      - name: beginner-html-site
        image: rupindervashisht/beginner-html-site:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: beginner-html-site-service
spec:
  type: NodePort
  selector:
    app: beginner-html-site
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
